stages:
  - release
  - publish

before_script:
  - npm config set @rfc:registry https://$REGISTRY_NPM_PRIVATE/
  - npm config set //$REGISTRY_NPM_PRIVATE/:_authToken=$NPM_TOKEN
  - npm install

release:
  stage: release
  image: node:13
  before_script:
    - npm install semantic-release @semantic-release/gitlab @semantic-release/changelog @semantic-release/git
  script:
    - NPM_APP_VERSION=$(node -p "require('./package.json').version")
    - GITLAB_TOKEN=$GITLAB_TOKEN NPM_TOKEN=$NPM_TOKEN semantic-release
    - npm version $NPM_APP_VERSION
  only:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE !~ /chore\(release\)/

publish:
  stage: publish
  image: node:13
  script:
    - npm publish
  after_script:
    - rm -rf .npmrc
  only:
    - tags
