image: node:13.11.0

stages:
  - release
  - publish

before_script:
  - npm config set @rfc:registry https://$REGISTRY_NPM_PRIVATE/
  - npm config set //$REGISTRY_NPM_PRIVATE/:_authToken=$NPM_TOKEN
  - npm install

release:
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install --global semantic-release @semantic-release/gitlab @semantic-release/changelog @semantic-release/git
  script:
    - NPM_APP_VERSION=$(node -p "require('./package.json').version")
    - GL_TOKEN=$GITLAB_TOKEN NPM_TOKEN=$NPM_TOKEN semantic-release
    - npm version $NPM_APP_VERSION
  only:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE !~ /chore\(release\)/

publish:
  stage: publish
  script:
    - npm publish
  after_script:
    - rm -rf .npmrc
  only:
    - tags
